const express = require('express');
const errors = require('./../../structs/errors')
const fs = require('fs');


const { CheckAuthorization } = require('../../middlewares/authorization');
const exp = require('constants');
const { ApiException } = errors;

const app = express.Router();

app.use(express.json())

const ServerStart = new Date();

const assets = {
    "FortCreativeDiscoverySurface": {
        "meta": {
            "promotion": 10
        },
        "assets": {
            "CreativeDiscoverySurface_Frontend": {
                "meta": {
                    "revision": 10,
                    "headRevision": 10,
                    "revisedAt": ServerStart.toISOString(),
                    "promotion": 10,
                    "promotedAt": ServerStart.toISOString()
                },
                "assetData": {
                    "TestCohorts": [
                        {
                            "CohortSelector": "PartyDeterministic",
                            "PlatformBlacklist": [],
                            "ContentPanels": [
                                {
                                    "NumPages": 2,
                                    "PanelType": "AnalyticsList",
                                    "AnalyticsListName": "byepic",
                                    "CuratedListOfLinkCodes": [],
                                    "ModelName": "",
                                    "PageSize": 10,
                                    "PlatformBlacklist": [],
                                    "PanelName": "ByEpic",
                                    "MetricInterval": "",
                                    "SkippedEntriesCount": 0,
                                    "SkippedEntriesPercent": 0,
                                    "SplicedEntries": [],
                                    "PlatformWhitelist": [],
                                    "EntrySkippingMethod": "None",
                                    "PanelDisplayName": {
                                        "Category": "Game",
                                        "NativeCulture": "",
                                        "Namespace": "CreativeDiscoverySurface_Frontend",
                                        "LocalizedStrings": [],
                                        "bIsMinimalPatch": false,
                                        "NativeString": "By Epic",
                                        "Key": "ByEpicPanel"
                                    },
                                    "PlayHistoryType": "RecentlyPlayed",
                                    "bLowestToHighest": false,
                                    "PanelLinkCodeBlacklist": [],
                                    "PanelLinkCodeWhitelist": [],
                                    "FeatureTags": [],
                                    "MetricName": ""
                                }
                            ],
                            "PlatformWhitelist": [],
                            "SelectionChance": 1,
                            "TestName": "NeoniteV3category"
                        }
                    ],
                    "GlobalLinkCodeBlacklist": [],
                    "SurfaceName": "CreativeDiscoverySurface_Frontend",
                    "primaryAssetId": "FortCreativeDiscoverySurface:CreativeDiscoverySurface_Frontend",
                    "GlobalLinkCodeWhitelist": []
                }
            }
        }
    },
    "DAD_CosmeticItemUserOptions": {
        "meta": {
            "promotion": 1
        },
        "assets": {}
    },
    "FortPlaylistAthena": {
        "meta": {
            "promotion": 3
        },
        "assets": {
            "Playlist_Papaya": {
                "meta": {
                    "revision": 2,
                    "headRevision": 2,
                    "revisedAt": "2021-10-20T19:14:52.648Z",
                    "promotion": 1,
                    "promotedAt": "2021-10-26T08:10:45.156Z"
                },
                "assetData": {
                    "bOwnerFilterDestructedBuildingsInGrid": false,
                    "bDisplayRespawnWidget": false,
                    "LootLevel": "1",
                    "bRequireCrossplayEnabled": true,
                    "ForceKickAfterDeathMode": "KickAll",
                    "bRequirePickaxeInStartingInventory": false,
                    "bRewardsAllowXPProgression": false,
                    "bVehiclesDestroyAllBuildingSMActorsOnContact": false,
                    "EndOfMatchXpFirstElim": "50",
                    "bEnableSpawningStartup": true,
                    "bAllowReturnToMatchmakingOriginOnMatchEnd": false,
                    "bShouldSpreadTeams": true,
                    "ServerPerClientMaxAI": "-1",
                    "LootDropRounds": "1",
                    "PlaylistName": "Playlist_Papaya",
                    "UIDisplaySubName": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "Squads",
                        "Key": "01558D9D405324A6F6517EBDAEE74EA4"
                    },
                    "bLimitedTimeMode": false,
                    "SafeZoneStartUp": "StartsWithNoAirCraft",
                    "AircraftPathOffsetFromMapCenterMax": "0.000000",
                    "ServerPerformanceEventFrequency": "300.000000",
                    "MaxBucketCapacity": "-1",
                    "MinTimeBeforeRespawnCameraFade": "3.000000",
                    "BuildingLevelOverride": "0",
                    "bIgnoreWeatherEvents": false,
                    "bUsesAnimationSharing": false,
                    "bForceCameraFadeOnRespawn": true,
                    "bAllowBotsInHumanTeams": false,
                    "bDisallowMultipleWeaponsOfType": false,
                    "DADTestValue": "0",
                    "bLeaderboardDisplaysIndividuals": true,
                    "bSkipAircraft": true,
                    "bAircraftDropOnlyWithinSafeZone": false,
                    "bDisableMatchStatsDisplay": false,
                    "bPlaylistUsesCustomCharacterParts": false,
                    "bOverrideServerPerClientMaxAI": false,
                    "bShowEliminationIndicatorForTeammates": false,
                    "RewardTimePlayedType": "NoReward",
                    "bAllowSpectateAPartyMember": false,
                    "CalendarEventsForEndOfMatchUpdate": [],
                    "MinPlayers": "1",
                    "bEnableCreativeMode": false,
                    "UnderfilledMaxPlayers": "32",
                    "MinBackfillMatchPlayers": "1",
                    "bIgnoreGameModeStartingInventory": false,
                    "bShowEliminationIndicatorForSelf": false,
                    "bTeamFilterDestructedBuildingsInGrid": true,
                    "LastStepPushAircraftCenterLine_Magnitude": "0.000000",
                    "bAllowBackfill": true,
                    "bUseInputRules": false,
                    "RewardTimePlayedXPPerMinute": "0",
                    "MinPlayersForPrivateServer": "0",
                    "ServerMetricsEventFrequency": "60.000000",
                    "bShouldFillWhenNoSquadFillOption": false,
                    "LastStepPushAircraftCenterLine_Direction": "0.000000",
                    "bEnableStatsV2Stats": true,
                    "bUseAsyncPhysics": false,
                    "bShowEliminationIndicatorForSquadmates": false,
                    "UIDescription": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "Welcome to the Party! Leave your weapons and mats behind and hang out with friends, play games, perfect your skydive and more. The party’s just getting started!",
                        "Key": "111DC8CF465BAD6CB6A4C4B60EFC9DF7"
                    },
                    "QuickbarSelectionPreservationMode": "KeepSelectionWhenRespawning",
                    "bWarmUpInStorm": false,
                    "bForceCustomMinigame": false,
                    "bUseFriendlyFireAimAssist": false,
                    "SkippedGamePhaseNotification": [],
                    "RatingType": "",
                    "CustomGameChannel": "Squad",
                    "bDisplayFinalStormPosition": false,
                    "bSkipWarmup": true,
                    "BotVersionPlaylistName": "",
                    "LastQueuedPlaylistPriority": "-1",
                    "AirCraftBehavior": "NoAircraft",
                    "bUseCustomAircraftPathSelection": false,
                    "bDrawCreativeDynamicIslands": false,
                    "MaximumAspectRatio": "0.000000",
                    "bShowTeamSelectButton": false,
                    "CurieManagerConfigOverrides": [],
                    "bRewardsTrackPlacement": false,
                    "LastSafeZoneIndex": "-1",
                    "bAllowJoinInProgress": true,
                    "WarmupEarlyRequiredPlayerPercent": "0.000000",
                    "bEnableRatingUpdate": false,
                    "bAllowHardcoreModifiers": false,
                    "bAllowPartyRift": true,
                    "bRespawnInAir": false,
                    "bUsePlayerRating": false,
                    "RichPresenceAssetName": "partyroyale",
                    "bUseLocalizationService": false,
                    "CompetitivePointClamp": "100",
                    "GameType": "Social",
                    "WinConditionPlayersRemaining": "1",
                    "TimeAfterWarmupToDisableBackfill": "5.000000",
                    "bUsePointLeaderAsTeamLeaderInLeaderboard": true,
                    "bRewardForRevivingTeammates": false,
                    "MaxSquads": "-1",
                    "bIsTournament": false,
                    "RewardsPlacementThreshold": "1",
                    "MaxTeamSize": "48",
                    "Strategy": "",
                    "bForceLTMLoadingScreenBackground": false,
                    "FriendlyFireType": "Off",
                    "bUseSameDirectionForOpposingAircraft": false,
                    "bEnableDynamicBotBackfill": false,
                    "bRequeueAfterFailedSessionAssignment": true,
                    "MaxHumanAndBotParticipants": "100",
                    "bAllowWarmupPlayerStartInSetupPhase": false,
                    "bShouldErrorOnAdditionalContentFailure": false,
                    "ForceKickAfterDeathTime": "20.000000",
                    "bSaveToRecentGameList": true,
                    "bAllowEditingEnemyWalls": false,
                    "JoinInProgressMatchType": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "",
                        "Key": ""
                    },
                    "bAccumulateToProfileStats": false,
                    "AircraftPathMidpointSelectionRadiusMin": "20000.000000",
                    "MaxPlayers": "48",
                    "bAllowedInLeto": false,
                    "bDisable_ReportAPlayerReason_TeamingUpWithEnemies_WhileInGame": false,
                    "bUseMultidivisionQueues": false,
                    "TypeOfLeaderboard": "Score",
                    "MaxSquadSize": "4",
                    "bAllowSquadFillOption": true,
                    "EndOfMatchXpMultiplier": "20",
                    "bForceNewPlayerStateOnReconnect": false,
                    "bDisableAudioShapes": false,
                    "bIsDefaultPlaylist": false,
                    "MapScaleOverride": "0.000000",
                    "bAllowInGameMatchMaking": true,
                    "MaxTeamScoreAllowedForBackfill": "0",
                    "bOverrideMaxPlayers": false,
                    "WinConditionType": "MutatorControlled",
                    "EnforceSquadFill": false,
                    "bEnableBackfillDuringWarmupPhase": true,
                    "bAllowBroadcasting": false,
                    "RewardTimePlayedXPFlatValue": "0",
                    "RespawnType": "InfiniteRespawnExceptStorm",
                    "bAllowLayoutRequirementsFeature": false,
                    "bAutoAcquireSpawnChip": false,
                    "bAllowKeepPlayingTogether": false,
                    "UIDisplayName": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "Party Royale",
                        "Key": "9BFE51FF49EA981A221BA6A114681440"
                    },
                    "GarbageCollectionFrequency": "300.000000",
                    "MaxPendingMatches": "-1",
                    "AircraftPathOffsetFromMapCenterMin": "0.000000",
                    "PlaylistStatId": "-1",
                    "NetActorDiscoveryBudgetInKBytesPerSec": "0",
                    "bShowEliminationIndicatorForEnemies": false,
                    "bLimitedPoolMatchmakingEnabled": false,
                    "MaxTeamScoreDiscrepancyPercent": "0.000000",
                    "PriorityRatingExpansion": [],
                    "bUseCreativeStarterIsland": false,
                    "bUnderfillMatchmaking": true,
                    "RequiredCatalogItemId": "",
                    "NonRenderedCharacterAnimationScale": "1.000000",
                    "bEnforceFullSquadInUI": false,
                    "bPreloadAthenaMapsForMatchmaking": true,
                    "primaryAssetId": "FortPlaylistAthena:Playlist_Papaya",
                    "bRemoveFromSquadOnLogout": true,
                    "FortReleaseVersion": {
                        "VersionName": "12.50"
                    },
                    "DBNOType": "On",
                    "StormEffectDelay": "0.000000",
                    "AircraftPathMidpointSelectionRadiusMax": "40000.000000",
                    "bAllowTeamSwitching": false,
                    "PlaylistId": "288",
                    "ServerMaxTickRate": "UseDefault",
                    "DestructedBuildingInGridTimeout": "0.000000",
                    "MaxSocialPartySize": "16",
                    "bAllowSinglePartyMatches": false,
                    "RewardPlacementBonusType": "LargeTeam",
                    "DefaultFirstTeam": "3",
                    "bAllowSquadSizeTracking": true,
                    "DefaultLastTeam": "102",
                    "bIsLargeTeamGame": false,
                    "bDrawLineToStormCircleIfOutside": true,
                    "bDisplayScoreInHUD": false,
                    "MaxTeamCount": "1",
                    "BuiltInGameFeaturePluginsToLoad": [
                        "PapayaHub",
                        "EventMode",
                        "PapayaPostersBackup",
                        "PapayaGameplay",
                        "MotherGround"
                    ],
                    "bActivateCurie": false,
                    "bUseDefaultSupplyDrops": true,
                    "bIgnoreDefaultQuests": true,
                    "bEnableBuildingCreatedEvent": false
                }
            },
            "Playlist_Sword_Solo": {
                "meta": {
                    "revision": 2,
                    "headRevision": 2,
                    "revisedAt": "2021-10-20T19:14:52.648Z",
                    "promotion": 1,
                    "promotedAt": "2021-10-26T08:10:45.156Z"
                },
                "assetData": {
                    "bOwnerFilterDestructedBuildingsInGrid": false,
                    "bDisplayRespawnWidget": false,
                    "LootLevel": "1",
                    "bRequireCrossplayEnabled": true,
                    "ForceKickAfterDeathMode": "KickAll",
                    "bRequirePickaxeInStartingInventory": false,
                    "bRewardsAllowXPProgression": false,
                    "bVehiclesDestroyAllBuildingSMActorsOnContact": false,
                    "EndOfMatchXpFirstElim": "50",
                    "bEnableSpawningStartup": true,
                    "bAllowReturnToMatchmakingOriginOnMatchEnd": false,
                    "bShouldSpreadTeams": true,
                    "ServerPerClientMaxAI": "-1",
                    "LootDropRounds": "1",
                    "PlaylistName": "Playlist_Papaya",
                    "UIDisplaySubName": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "Squads",
                        "Key": "01558D9D405324A6F6517EBDAEE74EA4"
                    },
                    "bLimitedTimeMode": false,
                    "SafeZoneStartUp": "StartsWithNoAirCraft",
                    "AircraftPathOffsetFromMapCenterMax": "0.000000",
                    "ServerPerformanceEventFrequency": "300.000000",
                    "MaxBucketCapacity": "-1",
                    "MinTimeBeforeRespawnCameraFade": "3.000000",
                    "BuildingLevelOverride": "0",
                    "bIgnoreWeatherEvents": false,
                    "bUsesAnimationSharing": false,
                    "bForceCameraFadeOnRespawn": true,
                    "bAllowBotsInHumanTeams": false,
                    "bDisallowMultipleWeaponsOfType": false,
                    "DADTestValue": "0",
                    "bLeaderboardDisplaysIndividuals": true,
                    "bSkipAircraft": true,
                    "bAircraftDropOnlyWithinSafeZone": false,
                    "bDisableMatchStatsDisplay": false,
                    "bPlaylistUsesCustomCharacterParts": false,
                    "bOverrideServerPerClientMaxAI": false,
                    "bShowEliminationIndicatorForTeammates": false,
                    "RewardTimePlayedType": "NoReward",
                    "bAllowSpectateAPartyMember": false,
                    "CalendarEventsForEndOfMatchUpdate": [],
                    "MinPlayers": "1",
                    "bEnableCreativeMode": false,
                    "UnderfilledMaxPlayers": "32",
                    "MinBackfillMatchPlayers": "1",
                    "bIgnoreGameModeStartingInventory": false,
                    "bShowEliminationIndicatorForSelf": false,
                    "bTeamFilterDestructedBuildingsInGrid": true,
                    "LastStepPushAircraftCenterLine_Magnitude": "0.000000",
                    "bAllowBackfill": true,
                    "bUseInputRules": false,
                    "RewardTimePlayedXPPerMinute": "0",
                    "MinPlayersForPrivateServer": "0",
                    "ServerMetricsEventFrequency": "60.000000",
                    "bShouldFillWhenNoSquadFillOption": false,
                    "LastStepPushAircraftCenterLine_Direction": "0.000000",
                    "bEnableStatsV2Stats": true,
                    "bUseAsyncPhysics": false,
                    "bShowEliminationIndicatorForSquadmates": false,
                    "UIDescription": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "Welcome to the Party! Leave your weapons and mats behind and hang out with friends, play games, perfect your skydive and more. The party’s just getting started!",
                        "Key": "111DC8CF465BAD6CB6A4C4B60EFC9DF7"
                    },
                    "QuickbarSelectionPreservationMode": "KeepSelectionWhenRespawning",
                    "bWarmUpInStorm": false,
                    "bForceCustomMinigame": false,
                    "bUseFriendlyFireAimAssist": false,
                    "SkippedGamePhaseNotification": [],
                    "RatingType": "",
                    "CustomGameChannel": "Squad",
                    "bDisplayFinalStormPosition": false,
                    "bSkipWarmup": true,
                    "BotVersionPlaylistName": "",
                    "LastQueuedPlaylistPriority": "-1",
                    "AirCraftBehavior": "NoAircraft",
                    "bUseCustomAircraftPathSelection": false,
                    "bDrawCreativeDynamicIslands": false,
                    "MaximumAspectRatio": "0.000000",
                    "bShowTeamSelectButton": false,
                    "CurieManagerConfigOverrides": [],
                    "bRewardsTrackPlacement": false,
                    "LastSafeZoneIndex": "-1",
                    "bAllowJoinInProgress": true,
                    "WarmupEarlyRequiredPlayerPercent": "0.000000",
                    "bEnableRatingUpdate": false,
                    "bAllowHardcoreModifiers": false,
                    "bAllowPartyRift": true,
                    "bRespawnInAir": false,
                    "bUsePlayerRating": false,
                    "RichPresenceAssetName": "partyroyale",
                    "bUseLocalizationService": false,
                    "CompetitivePointClamp": "100",
                    "GameType": "Social",
                    "WinConditionPlayersRemaining": "1",
                    "TimeAfterWarmupToDisableBackfill": "5.000000",
                    "bUsePointLeaderAsTeamLeaderInLeaderboard": true,
                    "bRewardForRevivingTeammates": false,
                    "MaxSquads": "-1",
                    "bIsTournament": false,
                    "RewardsPlacementThreshold": "1",
                    "MaxTeamSize": "48",
                    "Strategy": "",
                    "bForceLTMLoadingScreenBackground": false,
                    "FriendlyFireType": "Off",
                    "bUseSameDirectionForOpposingAircraft": false,
                    "bEnableDynamicBotBackfill": false,
                    "bRequeueAfterFailedSessionAssignment": true,
                    "MaxHumanAndBotParticipants": "100",
                    "bAllowWarmupPlayerStartInSetupPhase": false,
                    "bShouldErrorOnAdditionalContentFailure": false,
                    "ForceKickAfterDeathTime": "20.000000",
                    "bSaveToRecentGameList": true,
                    "bAllowEditingEnemyWalls": false,
                    "JoinInProgressMatchType": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "",
                        "Key": ""
                    },
                    "bAccumulateToProfileStats": true,
                    "AircraftPathMidpointSelectionRadiusMin": "20000.000000",
                    "MaxPlayers": "48",
                    "bAllowedInLeto": true,
                    "bDisable_ReportAPlayerReason_TeamingUpWithEnemies_WhileInGame": false,
                    "bUseMultidivisionQueues": true,
                    "TypeOfLeaderboard": "Score",
                    "MaxSquadSize": "4",
                    "bAllowSquadFillOption": true,
                    "EndOfMatchXpMultiplier": "20",
                    "bForceNewPlayerStateOnReconnect": true,
                    "bDisableAudioShapes": true,
                    "bIsDefaultPlaylist": true,
                    "MapScaleOverride": "0.000000",
                    "bAllowInGameMatchMaking": true,
                    "MaxTeamScoreAllowedForBackfill": "0",
                    "bOverrideMaxPlayers": true,
                    "WinConditionType": "MutatorControlled",
                    "EnforceSquadFill": false,
                    "bEnableBackfillDuringWarmupPhase": true,
                    "bAllowBroadcasting": true,
                    "RewardTimePlayedXPFlatValue": "0",
                    "RespawnType": "InfiniteRespawnExceptStorm",
                    "bAllowLayoutRequirementsFeature": true,
                    "bAutoAcquireSpawnChip": true,
                    "bAllowKeepPlayingTogether": true,
                    "UIDisplayName": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "Party Royale",
                        "Key": "9BFE51FF49EA981A221BA6A114681440"
                    },
                    "GarbageCollectionFrequency": "300.000000",
                    "MaxPendingMatches": "-1",
                    "AircraftPathOffsetFromMapCenterMin": "0.000000",
                    "PlaylistStatId": "-1",
                    "NetActorDiscoveryBudgetInKBytesPerSec": "0",
                    "bShowEliminationIndicatorForEnemies": true,
                    "bLimitedPoolMatchmakingEnabled": false,
                    "MaxTeamScoreDiscrepancyPercent": "0.000000",
                    "PriorityRatingExpansion": [],
                    "bUseCreativeStarterIsland": false,
                    "bUnderfillMatchmaking": true,
                    "RequiredCatalogItemId": "",
                    "NonRenderedCharacterAnimationScale": "1.000000",
                    "bEnforceFullSquadInUI": false,
                    "bPreloadAthenaMapsForMatchmaking": true,
                    "primaryAssetId": "FortPlaylistAthena:Playlist_Papaya",
                    "bRemoveFromSquadOnLogout": true,
                    "FortReleaseVersion": {
                        "VersionName": "12.50"
                    },
                    "DBNOType": "On",
                    "StormEffectDelay": "0.000000",
                    "AircraftPathMidpointSelectionRadiusMax": "40000.000000",
                    "bAllowTeamSwitching": false,
                    "PlaylistId": "288",
                    "ServerMaxTickRate": "UseDefault",
                    "DestructedBuildingInGridTimeout": "0.000000",
                    "MaxSocialPartySize": "16",
                    "bAllowSinglePartyMatches": false,
                    "RewardPlacementBonusType": "LargeTeam",
                    "DefaultFirstTeam": "3",
                    "bAllowSquadSizeTracking": true,
                    "DefaultLastTeam": "102",
                    "bIsLargeTeamGame": false,
                    "bDrawLineToStormCircleIfOutside": true,
                    "bDisplayScoreInHUD": false,
                    "MaxTeamCount": "1",
                    "BuiltInGameFeaturePluginsToLoad": [
                        "PapayaHub",
                        "EventMode",
                        "PapayaPostersBackup",
                        "PapayaGameplay",
                        "MotherGround"
                    ],
                    "bActivateCurie": false,
                    "bUseDefaultSupplyDrops": true,
                    "bIgnoreDefaultQuests": true,
                    "bEnableBuildingCreatedEvent": true
                }
            }
            ,
            "Playlist_BattleLab": {
                "meta": {
                    "revision": 2,
                    "headRevision": 2,
                    "revisedAt": "2021-10-15T15:05:20.176Z",
                    "promotion": 2,
                    "promotedAt": "2021-11-03T14:10:32.729Z"
                },
                "assetData": {
                    "bOwnerFilterDestructedBuildingsInGrid": false,
                    "bDisplayRespawnWidget": false,
                    "LootLevel": "3",
                    "bRequireCrossplayEnabled": true,
                    "ForceKickAfterDeathMode": "Disabled",
                    "bRequirePickaxeInStartingInventory": true,
                    "bRewardsAllowXPProgression": false,
                    "bVehiclesDestroyAllBuildingSMActorsOnContact": false,
                    "EndOfMatchXpFirstElim": "50",
                    "bEnableSpawningStartup": true,
                    "bAllowReturnToMatchmakingOriginOnMatchEnd": false,
                    "bShouldSpreadTeams": false,
                    "ServerPerClientMaxAI": "-1",
                    "LootDropRounds": "1",
                    "PlaylistName": "Playlist_BattleLab",
                    "UIDisplaySubName": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "",
                        "Key": ""
                    },
                    "bLimitedTimeMode": true,
                    "SafeZoneStartUp": "UseDefaultGameBehavior",
                    "AircraftPathOffsetFromMapCenterMax": "0.000000",
                    "ServerPerformanceEventFrequency": "300.000000",
                    "MaxBucketCapacity": "-1",
                    "MinTimeBeforeRespawnCameraFade": "1.000000",
                    "BuildingLevelOverride": "0",
                    "bIgnoreWeatherEvents": false,
                    "bUsesAnimationSharing": true,
                    "bForceCameraFadeOnRespawn": true,
                    "bAllowBotsInHumanTeams": false,
                    "bDisallowMultipleWeaponsOfType": false,
                    "DADTestValue": "0",
                    "bLeaderboardDisplaysIndividuals": true,
                    "bSkipAircraft": true,
                    "bAircraftDropOnlyWithinSafeZone": false,
                    "bDisableMatchStatsDisplay": false,
                    "bPlaylistUsesCustomCharacterParts": false,
                    "bOverrideServerPerClientMaxAI": false,
                    "bShowEliminationIndicatorForTeammates": false,
                    "RewardTimePlayedType": "Default",
                    "bAllowSpectateAPartyMember": false,
                    "CalendarEventsForEndOfMatchUpdate": [],
                    "MinPlayers": "1",
                    "bEnableCreativeMode": true,
                    "UnderfilledMaxPlayers": "0",
                    "MinBackfillMatchPlayers": "1",
                    "bIgnoreGameModeStartingInventory": false,
                    "bShowEliminationIndicatorForSelf": false,
                    "bTeamFilterDestructedBuildingsInGrid": true,
                    "LastStepPushAircraftCenterLine_Magnitude": "0.000000",
                    "bAllowBackfill": true,
                    "bUseInputRules": false,
                    "RewardTimePlayedXPPerMinute": "-1",
                    "MinPlayersForPrivateServer": "0",
                    "ServerMetricsEventFrequency": "60.000000",
                    "bShouldFillWhenNoSquadFillOption": false,
                    "LastStepPushAircraftCenterLine_Direction": "0.000000",
                    "bEnableStatsV2Stats": true,
                    "bUseAsyncPhysics": true,
                    "bShowEliminationIndicatorForSquadmates": false,
                    "UIDescription": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "Jump into your own Battle Royale island and set the rules! Select from favorite LTM loot pools, set up combat scenarios with the new Bot Grenades, and create your own mode by setting options like gravity and fall damage. Fill your game with up to 15 friends on your own island, or matchmake with default options in a public Battle Lab.",
                        "Key": "876DAA3B45975AB28055DFA4DCBA630E"
                    },
                    "QuickbarSelectionPreservationMode": "KeepSelectionWhenRespawning",
                    "bWarmUpInStorm": false,
                    "bForceCustomMinigame": false,
                    "bUseFriendlyFireAimAssist": true,
                    "SkippedGamePhaseNotification": [],
                    "RatingType": "",
                    "CustomGameChannel": "Squad",
                    "bDisplayFinalStormPosition": false,
                    "bSkipWarmup": true,
                    "BotVersionPlaylistName": "",
                    "LastQueuedPlaylistPriority": "-1",
                    "AirCraftBehavior": "Default",
                    "bUseCustomAircraftPathSelection": false,
                    "bDrawCreativeDynamicIslands": false,
                    "MaximumAspectRatio": "0.000000",
                    "bShowTeamSelectButton": true,
                    "CurieManagerConfigOverrides": [],
                    "bRewardsTrackPlacement": false,
                    "LastSafeZoneIndex": "-1",
                    "bAllowJoinInProgress": true,
                    "WarmupEarlyRequiredPlayerPercent": "0.000000",
                    "bEnableRatingUpdate": false,
                    "bAllowHardcoreModifiers": false,
                    "bAllowPartyRift": false,
                    "bRespawnInAir": true,
                    "bUsePlayerRating": false,
                    "RichPresenceAssetName": "battlelab",
                    "bUseLocalizationService": false,
                    "CompetitivePointClamp": "100",
                    "GameType": "Creative",
                    "WinConditionPlayersRemaining": "1",
                    "TimeAfterWarmupToDisableBackfill": "5.000000",
                    "bUsePointLeaderAsTeamLeaderInLeaderboard": true,
                    "bRewardForRevivingTeammates": false,
                    "MaxSquads": "-1",
                    "bIsTournament": false,
                    "RewardsPlacementThreshold": "1",
                    "MaxTeamSize": "16",
                    "Strategy": "",
                    "bForceLTMLoadingScreenBackground": false,
                    "FriendlyFireType": "Off",
                    "bUseSameDirectionForOpposingAircraft": false,
                    "bEnableDynamicBotBackfill": false,
                    "bRequeueAfterFailedSessionAssignment": true,
                    "MaxHumanAndBotParticipants": "-1",
                    "bAllowWarmupPlayerStartInSetupPhase": true,
                    "bShouldErrorOnAdditionalContentFailure": false,
                    "ForceKickAfterDeathTime": "0.000000",
                    "bSaveToRecentGameList": true,
                    "bAllowEditingEnemyWalls": false,
                    "JoinInProgressMatchType": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "",
                        "Key": ""
                    },
                    "bAccumulateToProfileStats": false,
                    "AircraftPathMidpointSelectionRadiusMin": "20000.000000",
                    "MaxPlayers": "16",
                    "bAllowedInLeto": false,
                    "bDisable_ReportAPlayerReason_TeamingUpWithEnemies_WhileInGame": false,
                    "bUseMultidivisionQueues": false,
                    "TypeOfLeaderboard": "Score",
                    "MaxSquadSize": "4",
                    "bAllowSquadFillOption": true,
                    "EndOfMatchXpMultiplier": "20",
                    "bForceNewPlayerStateOnReconnect": false,
                    "bDisableAudioShapes": false,
                    "bIsDefaultPlaylist": false,
                    "MapScaleOverride": "0.000000",
                    "bAllowInGameMatchMaking": true,
                    "MaxTeamScoreAllowedForBackfill": "0",
                    "bOverrideMaxPlayers": false,
                    "WinConditionType": "LastManStandingIncludingAllies",
                    "EnforceSquadFill": false,
                    "bEnableBackfillDuringWarmupPhase": true,
                    "bAllowBroadcasting": false,
                    "RewardTimePlayedXPFlatValue": "-1",
                    "RespawnType": "InfiniteRespawnExceptStorm",
                    "bAllowLayoutRequirementsFeature": true,
                    "bAutoAcquireSpawnChip": false,
                    "bAllowKeepPlayingTogether": false,
                    "UIDisplayName": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "Battle Lab",
                        "Key": "685CF16245DC144A11BF9C9D77CADA49"
                    },
                    "GarbageCollectionFrequency": "900.000000",
                    "MaxPendingMatches": "-1",
                    "AircraftPathOffsetFromMapCenterMin": "0.000000",
                    "PlaylistStatId": "35",
                    "NetActorDiscoveryBudgetInKBytesPerSec": "800",
                    "bShowEliminationIndicatorForEnemies": false,
                    "bLimitedPoolMatchmakingEnabled": false,
                    "MaxTeamScoreDiscrepancyPercent": "0.000000",
                    "PriorityRatingExpansion": [],
                    "bUseCreativeStarterIsland": true,
                    "bUnderfillMatchmaking": false,
                    "RequiredCatalogItemId": "",
                    "NonRenderedCharacterAnimationScale": "1.000000",
                    "bEnforceFullSquadInUI": false,
                    "bPreloadAthenaMapsForMatchmaking": true,
                    "primaryAssetId": "FortPlaylistAthena:Playlist_BattleLab",
                    "bRemoveFromSquadOnLogout": false,
                    "FortReleaseVersion": {
                        "VersionName": "11.31"
                    },
                    "DBNOType": "NotWhenRespawning",
                    "StormEffectDelay": "3240.000000",
                    "AircraftPathMidpointSelectionRadiusMax": "40000.000000",
                    "bAllowTeamSwitching": true,
                    "PlaylistId": "6635",
                    "ServerMaxTickRate": "UseDefault",
                    "DestructedBuildingInGridTimeout": "0.000000",
                    "MaxSocialPartySize": "16",
                    "bAllowSinglePartyMatches": true,
                    "RewardPlacementBonusType": "None",
                    "DefaultFirstTeam": "3",
                    "bAllowSquadSizeTracking": true,
                    "DefaultLastTeam": "19",
                    "bIsLargeTeamGame": false,
                    "bDrawLineToStormCircleIfOutside": false,
                    "bDisplayScoreInHUD": false,
                    "MaxTeamCount": "16",
                    "BuiltInGameFeaturePluginsToLoad": [
                        "Hitchhiker",
                        "MotherWall",
                        "Labrador",
                        "MotherGameplay",
                        "IO_Guard",
                        "Slone",
                        "MotherGround",
                        "NPCLibrary"
                    ],
                    "bActivateCurie": true,
                    "bUseDefaultSupplyDrops": false,
                    "bIgnoreDefaultQuests": true,
                    "bEnableBuildingCreatedEvent": false
                }
            },
            "Playlist_Toss_Trios": {
                "meta": {
                    "revision": 2,
                    "headRevision": 2,
                    "revisedAt": "2021-11-08T18:38:16.601Z",
                    "promotion": 3,
                    "promotedAt": "2021-11-08T20:07:27.153Z"
                },
                "assetData": {
                    "bOwnerFilterDestructedBuildingsInGrid": false,
                    "bDisplayRespawnWidget": false,
                    "LootLevel": "2",
                    "bRequireCrossplayEnabled": true,
                    "ForceKickAfterDeathMode": "Disabled",
                    "bRequirePickaxeInStartingInventory": true,
                    "bRewardsAllowXPProgression": true,
                    "bVehiclesDestroyAllBuildingSMActorsOnContact": false,
                    "EndOfMatchXpFirstElim": "50",
                    "bEnableSpawningStartup": true,
                    "bAllowReturnToMatchmakingOriginOnMatchEnd": false,
                    "bShouldSpreadTeams": true,
                    "ServerPerClientMaxAI": "-1",
                    "LootDropRounds": "1",
                    "PlaylistName": "Playlist_Toss_Trios",
                    "UIDisplaySubName": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "Trios",
                        "Key": "E948BB93450B8C4746B48B929947C983"
                    },
                    "bLimitedTimeMode": true,
                    "SafeZoneStartUp": "UseDefaultGameBehavior",
                    "AircraftPathOffsetFromMapCenterMax": "0.000000",
                    "ServerPerformanceEventFrequency": "0.000000",
                    "MaxBucketCapacity": "-1",
                    "MinTimeBeforeRespawnCameraFade": "3.000000",
                    "BuildingLevelOverride": "0",
                    "bIgnoreWeatherEvents": false,
                    "bUsesAnimationSharing": false,
                    "bForceCameraFadeOnRespawn": true,
                    "bAllowBotsInHumanTeams": false,
                    "bDisallowMultipleWeaponsOfType": false,
                    "DADTestValue": "0",
                    "bLeaderboardDisplaysIndividuals": true,
                    "bSkipAircraft": false,
                    "bAircraftDropOnlyWithinSafeZone": false,
                    "bDisableMatchStatsDisplay": false,
                    "bPlaylistUsesCustomCharacterParts": false,
                    "bOverrideServerPerClientMaxAI": false,
                    "bShowEliminationIndicatorForTeammates": false,
                    "RewardTimePlayedType": "Default",
                    "bAllowSpectateAPartyMember": false,
                    "CalendarEventsForEndOfMatchUpdate": [],
                    "MinPlayers": "20",
                    "bEnableCreativeMode": false,
                    "UnderfilledMaxPlayers": "0",
                    "MinBackfillMatchPlayers": "0",
                    "bIgnoreGameModeStartingInventory": false,
                    "bShowEliminationIndicatorForSelf": false,
                    "bTeamFilterDestructedBuildingsInGrid": true,
                    "LastStepPushAircraftCenterLine_Magnitude": "0.000000",
                    "bAllowBackfill": false,
                    "bUseInputRules": false,
                    "RewardTimePlayedXPPerMinute": "-1",
                    "MinPlayersForPrivateServer": "0",
                    "ServerMetricsEventFrequency": "60.000000",
                    "bShouldFillWhenNoSquadFillOption": false,
                    "LastStepPushAircraftCenterLine_Direction": "0.000000",
                    "bEnableStatsV2Stats": true,
                    "bUseAsyncPhysics": true,
                    "bShowEliminationIndicatorForSquadmates": false,
                    "UIDescription": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "In this mode, all guns have been removed. The only weapons are grenades and other items that can be thrown or tossed. Get in there and throw the enemies back to the lobby!",
                        "Key": "3BCD26A645D817F34B5222B88E820F38"
                    },
                    "QuickbarSelectionPreservationMode": "KeepSelectionWhenRespawning",
                    "bWarmUpInStorm": false,
                    "bForceCustomMinigame": false,
                    "bUseFriendlyFireAimAssist": false,
                    "SkippedGamePhaseNotification": [],
                    "RatingType": "",
                    "CustomGameChannel": "Squad",
                    "bDisplayFinalStormPosition": false,
                    "bSkipWarmup": false,
                    "BotVersionPlaylistName": "",
                    "LastQueuedPlaylistPriority": "-1",
                    "AirCraftBehavior": "Default",
                    "bUseCustomAircraftPathSelection": false,
                    "bDrawCreativeDynamicIslands": false,
                    "MaximumAspectRatio": "0.000000",
                    "bShowTeamSelectButton": false,
                    "CurieManagerConfigOverrides": [],
                    "bRewardsTrackPlacement": true,
                    "LastSafeZoneIndex": "-1",
                    "bAllowJoinInProgress": false,
                    "WarmupEarlyRequiredPlayerPercent": "0.000000",
                    "bEnableRatingUpdate": false,
                    "bAllowHardcoreModifiers": false,
                    "bAllowPartyRift": false,
                    "bRespawnInAir": true,
                    "bUsePlayerRating": false,
                    "RichPresenceAssetName": "",
                    "bUseLocalizationService": false,
                    "CompetitivePointClamp": "100",
                    "GameType": "BRLTM",
                    "WinConditionPlayersRemaining": "1",
                    "TimeAfterWarmupToDisableBackfill": "5.000000",
                    "bUsePointLeaderAsTeamLeaderInLeaderboard": true,
                    "bRewardForRevivingTeammates": false,
                    "MaxSquads": "-1",
                    "bIsTournament": false,
                    "RewardsPlacementThreshold": "5",
                    "MaxTeamSize": "3",
                    "Strategy": "",
                    "bForceLTMLoadingScreenBackground": false,
                    "FriendlyFireType": "Off",
                    "bUseSameDirectionForOpposingAircraft": false,
                    "bEnableDynamicBotBackfill": false,
                    "bRequeueAfterFailedSessionAssignment": true,
                    "MaxHumanAndBotParticipants": "-1",
                    "bAllowWarmupPlayerStartInSetupPhase": true,
                    "bShouldErrorOnAdditionalContentFailure": false,
                    "ForceKickAfterDeathTime": "0.000000",
                    "bSaveToRecentGameList": true,
                    "bAllowEditingEnemyWalls": false,
                    "JoinInProgressMatchType": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "",
                        "Key": ""
                    },
                    "bAccumulateToProfileStats": true,
                    "AircraftPathMidpointSelectionRadiusMin": "20000.000000",
                    "MaxPlayers": "99",
                    "bAllowedInLeto": false,
                    "bDisable_ReportAPlayerReason_TeamingUpWithEnemies_WhileInGame": false,
                    "bUseMultidivisionQueues": false,
                    "TypeOfLeaderboard": "Score",
                    "MaxSquadSize": "3",
                    "bAllowSquadFillOption": true,
                    "EndOfMatchXpMultiplier": "20",
                    "bForceNewPlayerStateOnReconnect": false,
                    "bDisableAudioShapes": false,
                    "bIsDefaultPlaylist": false,
                    "MapScaleOverride": "0.000000",
                    "bAllowInGameMatchMaking": true,
                    "MaxTeamScoreAllowedForBackfill": "0",
                    "bOverrideMaxPlayers": false,
                    "WinConditionType": "LastManStanding",
                    "EnforceSquadFill": true,
                    "bEnableBackfillDuringWarmupPhase": true,
                    "bAllowBroadcasting": false,
                    "RewardTimePlayedXPFlatValue": "-1",
                    "RespawnType": "None",
                    "bAllowLayoutRequirementsFeature": false,
                    "bAutoAcquireSpawnChip": false,
                    "bAllowKeepPlayingTogether": false,
                    "UIDisplayName": {
                        "Category": "Game",
                        "NativeCulture": "",
                        "Namespace": "",
                        "LocalizedStrings": [],
                        "bIsMinimalPatch": false,
                        "NativeString": "Throwdown",
                        "Key": "2CC2F3F84BBC2FFB9A725EAA8509989F"
                    },
                    "GarbageCollectionFrequency": "0.000000",
                    "MaxPendingMatches": "-1",
                    "AircraftPathOffsetFromMapCenterMin": "0.000000",
                    "PlaylistStatId": "-1",
                    "NetActorDiscoveryBudgetInKBytesPerSec": "0",
                    "bShowEliminationIndicatorForEnemies": false,
                    "bLimitedPoolMatchmakingEnabled": false,
                    "MaxTeamScoreDiscrepancyPercent": "0.000000",
                    "PriorityRatingExpansion": [],
                    "bUseCreativeStarterIsland": false,
                    "bUnderfillMatchmaking": false,
                    "RequiredCatalogItemId": "",
                    "NonRenderedCharacterAnimationScale": "1.000000",
                    "bEnforceFullSquadInUI": false,
                    "bPreloadAthenaMapsForMatchmaking": true,
                    "primaryAssetId": "FortPlaylistAthena:Playlist_Toss_Trios",
                    "bRemoveFromSquadOnLogout": false,
                    "FortReleaseVersion": {
                        "VersionName": "18.30"
                    },
                    "DBNOType": "On",
                    "StormEffectDelay": "0.000000",
                    "AircraftPathMidpointSelectionRadiusMax": "40000.000000",
                    "bAllowTeamSwitching": false,
                    "PlaylistId": "341",
                    "ServerMaxTickRate": "Twenty",
                    "DestructedBuildingInGridTimeout": "0.000000",
                    "MaxSocialPartySize": "3",
                    "bAllowSinglePartyMatches": false,
                    "RewardPlacementBonusType": "Squad",
                    "DefaultFirstTeam": "3",
                    "bAllowSquadSizeTracking": true,
                    "DefaultLastTeam": "102",
                    "bIsLargeTeamGame": false,
                    "bDrawLineToStormCircleIfOutside": true,
                    "bDisplayScoreInHUD": false,
                    "MaxTeamCount": "99",
                    "BuiltInGameFeaturePluginsToLoad": [],
                    "bActivateCurie": true,
                    "bUseDefaultSupplyDrops": true,
                    "bIgnoreDefaultQuests": false,
                    "bEnableBuildingCreatedEvent": false
                }
            }
        }
    }
}

app.get('/region', CheckAuthorization, (req, res) => {
    res.json({
        "continent": {
            "code": "NA",
            "geoname_id": 6255149,
            "names": {
                "de": "Nordamerika",
                "en": "North America",
                "es": "Norteamérica",
                "fr": "Amérique du Nord",
                "ja": "北アメリカ",
                "pt-BR": "América do Norte",
                "ru": "Северная Америка",
                "zh-CN": "北美洲"
            }
        },
        "country": {
            "geoname_id": 6251999,
            "is_in_european_union": false,
            "iso_code": "CA",
            "names": {
                "de": "Kanada",
                "en": "Canada",
                "es": "Canadá",
                "fr": "Canada",
                "ja": "カナダ",
                "pt-BR": "Canadá",
                "ru": "Канада",
                "zh-CN": "加拿大"
            }
        },
        "subdivisions": [
        ]
    })
})

app.post('/api/v1/assets/Fortnite/:version/:netcl', CheckAuthorization, (req, res) => {
    const wantedKeys = Object.keys(req.body);

    res.json(
        Object.fromEntries(
            Object.entries(assets)
                .filter(([key, value]) => wantedKeys.includes(key))
        )
    )
});

// prm
app.post('/api/v1/fortnite-br/surfaces/motd/target', (req, res) => {
    res.json({
        "contentType": "collection",
        "contentId": "motd-default-collection",
        "tcId": "8d0db258-2862-40c9-9c24-0eeb3782a2ff",
        "contentItems": [
            {
                "contentType": "content-item",
                "contentId": "1bd29db9-11da-420f-85ae-8f7e9b6143b7",
                "tcId": "d306ebdb-7740-45a8-9db6-074dcfcc31fc",
                "contentFields": {
                    "body": "From the smoldering wreckage of the Mothership a new threat arises. Cubes are waking up and spreading corruption. It’s up to you to fight for the Island’s survival.",
                    "buttonTextOverride": "Play Now",
                    "category": "Narrative",
                    "entryType": "Text",
                    "image": [
                        {
                            "width": 1920,
                            "height": 1080,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/BR_KeyArt_Social_MOT-77bf920b-2baf-45fd-beb9-e8785869419c.jpeg?width=1920"
                        },
                        {
                            "width": 960,
                            "height": 540,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/BR_KeyArt_Social_MOT-77bf920b-2baf-45fd-beb9-e8785869419c.jpeg?width=960"
                        }
                    ],
                    "islandCode": "Playlist_Solo",
                    "tabTitleOverride": "Chapter 2 Season 8",
                    "tileImage": [
                        {
                            "width": 1024,
                            "height": 512,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/BR_KeyArt_Social_MOT-38c146c7-8b0a-445b-b414-fe6f6f6f2a1f.jpeg?width=1024"
                        }
                    ],
                    "title": "Cubed"
                },
                "contentSchemaName": "DiscoveryMotd",
                "contentSchemaVersion": 1
            },
            {
                "contentType": "content-item",
                "contentId": "be506bde-4f3b-46fb-87f6-e66b285f66f9",
                "tcId": "78802f7c-990a-473a-a7ef-23f5a1853fd8",
                "contentFields": {
                    "body": "Enter a Sideways Anomaly and travel to a mysterious and dangerous world where the rules are different: gravity is low and building is non-existent.",
                    "buttonTextOverride": "Play Now",
                    "category": "Featured",
                    "entryType": "Text",
                    "image": [
                        {
                            "width": 1920,
                            "height": 1080,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/S_SS_BP_x_jpg-428dca1e-1f61-4449-b703-f5ffe4baad5b.jpeg?width=1920"
                        },
                        {
                            "width": 960,
                            "height": 540,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/S_SS_BP_x_jpg-428dca1e-1f61-4449-b703-f5ffe4baad5b.jpeg?width=960"
                        }
                    ],
                    "islandCode": "Playlist_Solo",
                    "tileImage": [
                        {
                            "width": 1024,
                            "height": 512,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/S_SS_BP_x_jpg-910d699e-56c6-49eb-b18e-28f9e36a0885.jpeg?width=1024"
                        }
                    ],
                    "title": "Battle the Sideways"
                },
                "contentSchemaName": "DiscoveryMotd",
                "contentSchemaVersion": 1
            },
            {
                "contentType": "content-item",
                "contentId": "687ea6ee-fd32-441e-b0d0-67dc865ee56a",
                "tcId": "6bb0da94-bb1f-4096-9c19-42542471148b",
                "contentFields": {
                    "body": "There’s a new way to complete quests with friends! Party up to share quests and adventure through Quest Punchcards together.",
                    "buttonTextOverride": "View Quests",
                    "challengeCategoryTag": "ChallengeCategory.XP",
                    "entryType": "Challenge",
                    "image": [
                        {
                            "width": 1920,
                            "height": 1080,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/BR_XP_Weekly_Quests_-658e2fe1-c217-42e4-91db-075415964f6e.jpeg?width=1920"
                        },
                        {
                            "width": 960,
                            "height": 540,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/BR_XP_Weekly_Quests_-658e2fe1-c217-42e4-91db-075415964f6e.jpeg?width=960"
                        }
                    ],
                    "tileImage": [
                        {
                            "width": 1024,
                            "height": 512,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/BR_XP_Weekly_Quests_-a4e8d4ba-ae67-4304-8c80-1842162a723e.jpeg?width=1024"
                        }
                    ],
                    "title": "Quests & Punchcards"
                },
                "contentSchemaName": "MotdNavigateToChallenge",
                "contentSchemaVersion": 1
            },
            {
                "contentType": "content-item",
                "contentId": "5edbd460-7a93-4244-b302-4ff6ceadca06",
                "tcId": "3d579871-e7cc-40fd-ac65-9426f3a66a86",
                "contentFields": {
                    "body": "Join Fortnite Crew to get the exclusive Crew Legacy Set, including a customizable Back Bling and unlockable Pickaxe. Earn new styles each month you’re part of the Crew!",
                    "buttonTextOverride": "Join Fortnite Crew",
                    "entryType": "RTFItem",
                    "image": [
                        {
                            "width": 1920,
                            "height": 1080,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/6d818586c9eeca2786827b2cee714bdce42a60b185b9094ad7e3e6da1a3a939da808b74731d0550876f8ecd3f191ff3f8853b1cd06a57576c95069c8658ade42-e7bc7236-78bf-4af3-aeb7-cc6e77217457.jpeg?width=1920"
                        },
                        {
                            "width": 960,
                            "height": 540,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/6d818586c9eeca2786827b2cee714bdce42a60b185b9094ad7e3e6da1a3a939da808b74731d0550876f8ecd3f191ff3f8853b1cd06a57576c95069c8658ade42-e7bc7236-78bf-4af3-aeb7-cc6e77217457.jpeg?width=960"
                        }
                    ],
                    "offerAction": "NavigateToOffer",
                    "offerId": "AE1A98314BFD6F057A4D5785916058DD ",
                    "tabTitleOverride": "Crew Legacy Set",
                    "tileImage": [
                        {
                            "width": 1024,
                            "height": 512,
                            "url": "https://cdn-live.prm.ol.epicgames.com/prod/6d818586c9eeca2786827b2cee714bdce42a60b185b9094ad7e3e6da1a3a939d1309381e61ca333e70024509de190ce959e07d7aa20f75f132d916c4783b0a0f-77dabf64-da7d-46c0-a31c-a45b44af3aa4.jpeg?width=1024"
                        }
                    ],
                    "title": "Protocol Pack & Zen Axe",
                    "videoAutoplay": false,
                    "videoLoop": false,
                    "videoMute": false,
                    "videoStreamingEnabled": false
                },
                "contentSchemaName": "MotdItemWithVideo",
                "contentSchemaVersion": 1
            }
        ]
    })
})

app.post('/profile/privacy_settings', CheckAuthorization, (req, res) => {
    res.json({
        "privacySettings": {
            "playRegion": "UNDEFINED_LEVEL",
            "badges": "UNDEFINED_LEVEL",
            "languages": "UNDEFINED_LEVEL"
        }
    })
})

module.exports = app;

